import crypto from 'crypto';

export interface StreamUserTokenOptions { userId:string; name?:string; role?:string; expirationSeconds?:number; }
export interface StreamChannelMember { userId:string; name:string; avatar?:string; language?:string; role:'admin'|'member'|'guest'; online?:boolean; }
export interface StreamReaction { type:string; userId:string; userName:string; timestamp:number; }
export interface StreamChatMessage { id:string; channelId:string; userId:string; userName:string; userAvatar?:string; text:string; translatedText?:string; targetLang?:string; sourceLang?:string; createdAt:number; reactions:StreamReaction[]; attachments?:Array<{type:'image'|'audio'|'file';url:string;name?:string;size?:string}>; isVoiceNote?:boolean; voiceNoteDuration?:number; }
export interface StreamChannelData { id:string; type:string; name:string; members:StreamChannelMember[]; custom?:Record<string,any>; lastMessage?:string; lastMessageAt?:number; updatedAt:number; unreadCount?:number; }
export interface StreamEventLog { id:string; type:string; channelId?:string; userId?:string; payload:any; timestamp:number; }

function cfg(){const apiKey=process.env.STREAM_API_KEY,secret=process.env.STREAM_API_SECRET;if(!apiKey||!secret)throw new Error('GetStream production credentials are not configured.');return {apiKey,secret,base:(process.env.STREAM_API_BASE_URL||'https://chat.stream-io-api.com').replace(/\/$/,'')};}
function b64(v:Buffer|string){return Buffer.from(v).toString('base64url');}
function tokenFor(userId:string,exp:number){const {secret}=cfg();const iat=Math.floor(Date.now()/1000);const head=b64(JSON.stringify({alg:'HS256',typ:'JWT'}));const body=b64(JSON.stringify({user_id:userId,user:{id:userId},iat,exp}));const sig=b64(crypto.createHmac('sha256',secret).update(`${head}.${body}`).digest());return `${head}.${body}.${sig}`;}
async function streamRequest(path:string,method='POST',body?:any,userId='server'){const {apiKey,base}=cfg();const exp=Math.floor(Date.now()/1000)+3600;const headers={'Content-Type':'application/json','Stream-Auth-Type':'jwt','Authorization':tokenFor(userId,exp)};const r=await fetch(`${base}${path}${path.includes('?')?'&':'?'}api_key=${encodeURIComponent(apiKey)}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const raw=await r.text();let data:any={};try{data=raw?JSON.parse(raw):{};}catch{data={raw};}if(!r.ok)throw new Error(data?.message||data?.error||`GetStream request failed (${r.status})`);return data;}
function ensureId(id:string){return id.replace(/^messaging:/,'');}
function mapMessage(m:any,channelId:string):StreamChatMessage{return{id:m.id,channelId,userId:m.user?.id||m.user_id||'',userName:m.user?.name||m.user_id||'',userAvatar:m.user?.image,text:m.text||'',translatedText:m.translatedText||m.translated_text,targetLang:m.targetLang||m.target_lang,sourceLang:m.sourceLang||m.source_lang,createdAt:m.created_at?new Date(m.created_at).getTime():Date.now(),reactions:(m.latest_reactions||[]).map((r:any)=>({type:r.type,userId:r.user_id,userName:r.user_id,timestamp:Date.now()})),attachments:(m.attachments||[]).map((a:any)=>({type:a.type==='image'?'image':a.type==='video'?'file':'file',url:a.asset_url||a.image_url||a.url||'',name:a.title,size:a.file_size?String(a.file_size):undefined})),isVoiceNote:Boolean(m.isVoiceNote||m.is_voice_note),voiceNoteDuration:Number(m.voiceNoteDuration||m.voice_note_duration||0)||undefined};}
export function generateStreamUserToken(options:StreamUserTokenOptions){const {apiKey}=cfg();const seconds=Math.min(options.expirationSeconds||3600,86400);const token=tokenFor(options.userId,Math.floor(Date.now()/1000)+seconds);return{token,apiKey,userId:options.userId,expiresAt:Date.now()+seconds*1000,isMock:false};}
export async function upsertStreamChannel(c:StreamChannelData){const id=ensureId(c.id);await streamRequest(`/channels/${encodeURIComponent(c.type||'messaging')}/${encodeURIComponent(id)}/query`,'POST',{watch:false,state:false,presence:false,members:{limit:100},data:{name:c.name,...c.custom},add_members:c.members.map(m=>m.userId)},c.members[0]?.userId||'server');return c;}
export async function getStreamChannel(channelId:string){const id=ensureId(channelId);try{const d=await streamRequest(`/channels/messaging/${encodeURIComponent(id)}/query`,'POST',{watch:false,state:true,presence:false,messages:{limit:1},members:{limit:100}},'server');const ch=d.channel||{};const members=Object.values(d.members||{}).map((m:any)=>({userId:m.user_id,name:m.user?.name||m.user_id,avatar:m.user?.image,role:m.role||'member'}));const m=d.messages?.[0];return{id,type:'messaging',name:ch.name||id,members,updatedAt:m?.created_at?new Date(m.created_at).getTime():Date.now(),lastMessage:m?.text,lastMessageAt:m?.created_at?new Date(m.created_at).getTime():undefined};}catch{return null;}}
export async function getStreamMessages(channelId:string){const id=ensureId(channelId);const d=await streamRequest(`/channels/messaging/${encodeURIComponent(id)}/query`,'POST',{watch:false,state:true,presence:false,messages:{limit:50}},'server');return(d.messages||[]).map((m:any)=>mapMessage(m,id));}
export async function addStreamMessage(channelId:string,message:StreamChatMessage){const id=ensureId(channelId);const d=await streamRequest(`/channels/messaging/${encodeURIComponent(id)}/message`,'POST',{message:{text:message.text,attachments:message.attachments||[],sourceLang:message.sourceLang,targetLang:message.targetLang,translatedText:message.translatedText,isVoiceNote:message.isVoiceNote,voiceNoteDuration:message.voiceNoteDuration,user:{id:message.userId}}},message.userId);return mapMessage(d.message,id);}
export async function toggleStreamReaction(channelId:string,messageId:string,reactionType:string,userId:string,userName:string){const id=ensureId(channelId);const messages=await getStreamMessages(id);const m=messages.find(x=>x.id===messageId);if(!m)return null;const has=m.reactions.some(r=>r.userId===userId&&r.type===reactionType);if(has)await streamRequest(`/channels/messaging/${encodeURIComponent(id)}/message/${encodeURIComponent(messageId)}/reaction/${encodeURIComponent(reactionType)}/${encodeURIComponent(userId)}`,'DELETE',undefined,userId);else await streamRequest(`/channels/messaging/${encodeURIComponent(id)}/message/${encodeURIComponent(messageId)}/reaction`,'POST',{reaction:{type:reactionType,user_id:userId}},userId);return (await getStreamMessages(id)).find(x=>x.id===messageId)||null;}
export async function getActiveStreamChannels(userId?:string){ if(!userId) return []; const d=await streamRequest('/channels/messaging/query','POST',{filter:{members:{$in:[userId]}},sort:[{field:'last_message_at',direction:-1}],limit:100},userId); return (d.channels||[]).map((x:any)=>({id:x.channel?.id||x.cid?.split(':')[1],type:x.channel?.type||'messaging',name:x.channel?.name||x.channel?.id||x.cid,members:Object.values(x.members||{}).map((m:any)=>({userId:m.user_id,name:m.user?.name||m.user_id,avatar:m.user?.image,role:m.role||'member'})),updatedAt:x.channel?.updated_at?new Date(x.channel.updated_at).getTime():Date.now(),lastMessage:x.channel?.last_message?.text,lastMessageAt:x.channel?.last_message?.created_at?new Date(x.channel.last_message.created_at).getTime():undefined})); }
export function getStreamEventLogs(){return[];}
export function recordStreamEvent(){return;}
